## **NUMPY**

- Numerical Python
- **Library** of python
- Helps us create **N-Dimensional Arrays**
- Allows us to perform Numerical Computation/ Calculations
- 
- 
- 
- Matrix in High School - Pro SOON 

In [ ]:
import math

import sys

import os

In [77]:
import datetime

# Get today's date and current time

today = datetime.date.today()

current_time = datetime.datetime.now().time()

print(f"Today's Date: {today}, \nCurrent Time: {current_time}")

Today's Date: 2026-01-29, 
Current Time: 08:43:28.968126


### How to use this library

In [1]:
import numpy as np

np.__version__

'2.4.1'

In [ ]:
# abstraction means - hide the unnecessary details
# just use what you need

### Objects that we create with numpy are `nd.arrays`
- like other objects we say 
- objects simply belong to a class
- TextIOWrapper object, Range Object, InstructorObject
- MappingObject
- 
- **ARRAYs**
- belong to nd.arrays

In [ ]:
x = np.array(1)

# if you want to feed more than one number or characters into it, use sequence type data

type(x)

We have another type of array in python as well
- we use Array module to create those arrays
- these arrays are fast
- only allow a single type of data - homogenous

In [ ]:
# we have an array module

from array import array

# a single type of data
nums = array('i',[1,2,3,4,5,6])
type(nums)



List has issues
- not as memory optimzed
- not as fast

With Numpy Arrays
- flexibility of lists
- fast operations and memory optimizations of arrays
- operations that Numpy has in its modules

In [ ]:
# standard way of createing an array
python_list = [1,2,3,4,5]

array_1 = np.array(python_list)
print(python_list)
print(array_1)
type(array_1)

In [4]:
# N - Dimensions

# 1 Dimenstional Array
list_1D = [x for x in range(10)]

array_1D = np.array(list_1D)

print(array_1D, "\nnumber of dimension is: ",array_1D.ndim)

# access elements within a list , [ ]
list_1D[1]
array_1D[4]

[0 1 2 3 4 5 6 7 8 9] 
number of dimension is:  1


np.int64(4)

In [8]:
# 2 Dimenstional Array
list_2D = [list_1D, list_1D]

array_2D = np.array(list_2D)

print(array_2D,"\nnumber of dimension is: ", array_2D.ndim)
print(list_2D)

list_2D[1][5]

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]] 
number of dimension is:  2
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]


5

In [21]:
# 3 Dimenstional Array
list_3D = [list_2D, list_2D, list_2D]

array_3D = np.array(list_3D)

print(array_3D,"\nnumber of dimension is: ", array_3D.ndim)
print(list_3D)

list_3D[2][1][9]

[[[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]] 
number of dimension is:  3
[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]], [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]


9

In [ ]:
array_1D.ndim # works on arrays

list_1D.ndim # ndim is an array method, not a list method

AttributeError: 'list' object has no attribute 'ndim'

In [31]:
len(array_1D)

10

In [28]:
len(list_1D)

8

### Array Attributes/Properties
- .ndim - number of dimensions
- .shape - ( rows , columns )
- .size - how many elemetns
- .dtype - type of data stored in array
- 

In [ ]:
array_2D.ndim # dimensions


# shape ==== ( rows , columns )
array_1D.shape   # (10, )
array_2D.shape # (2, 10)
array_3D.shape # (3,2,10)

array_2D.dtype

np.int64(9)

In [37]:
array_fruits = np.array(['apple', 'banana', 'orange'])

array_fruits.dtype

dtype('<U6')

### Array Methods

In [ ]:
# use np.arange

arr = np.arange(10)
print(arr)


# np.array_split()
arr_parts = np.array_split(arr, 3)
print("======arr_parts=====")
for part in arr_parts:
    print(part)

[0 1 2 3 4 5 6 7 8 9]
======arr_parts=====
[0 1 2 3]
[4 5 6]
[7 8 9]


In [50]:
# Linspace  -- evenly spaced values
# start, stop, num
# if 10,50, 5 --> start from 10, ending will 50 ---> INCLUSIVE 
line = np.linspace(10,50,5)
print("linspace of line: ", line)

linspace of line:  [10. 20. 30. 40. 50.]


In [66]:
# zeros and ones methods
# pass any shape, ---> rows x columns
print("--------------Zeros Matrix---------------")
a = np.zeros((3,2,3))
print(a)

print("--------------Ones Matrix---------------")
b = np.ones((3,3))
print(b)

print("--------------Identity Matrix------------")
identiy_matrix = np.eye(3) # rows = columns identity matrix
print(identiy_matrix)

--------------Zeros Matrix---------------
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
--------------Ones Matrix---------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------Identity Matrix------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Random
- generation of random numbers
- random number 

In [253]:
# set a seed -- choose a starting point for the generator function
np.random.seed(1)       # helps us make our results, Reproducable

# random values --- from [0, 1)]
random_floats = np.random.rand(2,3,3) 
print(random_floats)


# start point, end point --- radnom number between them --- of shape
random_integers = np.random.randint(0,9)            # random number from 0 to 9
random_integers = np.random.randint(0,9,(10,))      # random array of numbers
random_integers = np.random.randint(0,9,(3,3))
print("--------------random_integers------------")
print(random_integers)

[[[4.17022005e-01 7.20324493e-01 1.14374817e-04]
  [3.02332573e-01 1.46755891e-01 9.23385948e-02]
  [1.86260211e-01 3.45560727e-01 3.96767474e-01]]

 [[5.38816734e-01 4.19194514e-01 6.85219500e-01]
  [2.04452250e-01 8.78117436e-01 2.73875932e-02]
  [6.70467510e-01 4.17304802e-01 5.58689828e-01]]]
--------------random_integers------------
[[8 7 3]
 [6 5 1]
 [3 4 8]]


#### Slicing

In [ ]:
# slice lists
list_1D[1:5] # 
list_1D[1:5:2] 
list_1D[1::]
list_1D[:]  

# list_2D[0, 1] # does not work
list_2D[0:2][:5]
# list does not really support submatrix



[[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]]

In [ ]:
# slice arrays
array_1D[1:5] # works 
array_1D[1:5:2] # start: stop: step  # works

array_1D[1::]
array_1D[:]

array_2D[0,] # [ 1st array, 2nd array  ]# works here

array_2D


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
# rows columns
array_2D[0:2][:5]

# if using comma, think about rows, columns
array_2D[1 , :5]


# SUBMATRIX --- rows, columns
array_2D[: , :5] # all rows , only 0 to 5 columns


array_3D[1:,0:1,:5] # 1d array, 2d array, 3d array

array([[[0, 1, 2, 3, 4]],

       [[0, 1, 2, 3, 4]]])

array([[2, 3, 4, 5, 6],
       [2, 3, 4, 5, 6]])

#### View vs Copy

#### Reshape, Flatten, Transpose

#### Operations and Broadcasting

#### Aggregations 
- SUM MEAN MIN MAX STD VAR
- Agg along axis

#### OPTIONAL - Matrix multiply and Dot